name: Build and Release
# If Action doesn't run, check: https://www.githubstatus.com/
on:
  workflow_dispatch: 
  push:
    branches: [ "main" ]
    paths:
      - '**.go'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.go'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Set revision environment variable
        run: |
          REVISION=$(git rev-parse --short HEAD)
          echo "REVISION=$REVISION" >> $GITHUB_ENV

      - name: Build for Ubuntu
        run: GOOS=linux go build -o tsi-linux *.go
      
      - name: Build for Mac Darwin
        run: GOOS=darwin go build -o tsi-darwin *.go

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        # env:
        #   TSI_GITHUB_TOKEN: ${{ secrets.TSI_GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.REVISION }}
          release_name: Release v${{ env.REVISION }}

          body: |
            Changes in this release:
            ${{ join(github.event.commits.*.message, '\n- ') }}
          draft: false
          prerelease: false
          token: ${{secrets.TSI_GITHUB_TOKEN}}
      - name: Upload Linux Binary
        uses: actions/upload-release-asset@v1
        # env:
        #   TSI_GITHUB_TOKEN: ${{ secrets.TSI_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tsi-linux
          asset_name: tsi-linux
          asset_content_type: application/octet-stream
          token: ${{secrets.TSI_GITHUB_TOKEN}}

      - name: Upload Darwin Binary
        uses: actions/upload-release-asset@v1
        # env:
        #   TSI_GITHUB_TOKEN: ${{ secrets.TSI_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tsi-darwin
          asset_name: tsi-darwin
          asset_content_type: application/octet-stream
          token: ${{secrets.TSI_GITHUB_TOKEN}}